"""Module to handle notification actions for New Users, Password Changes and Source Additions."""

import smtplib
from email.mime.text import MIMEText
from cryptography.fernet import Fernet
import dbconnection as dbc

RED = '\033[91m' # Erorr Messages
GREEN = '\033[92m' # Success Messages

OUTBND_EMAIL =  'suspect.sources@gmail.com'
OUTBND_ENC_PSWD = b'gAAAAABgbavwJiy3quTfBs44koynkhs5sNYVETrSeh-aTlFl3HH8LSMvtC0-09fkvqdyTgJJ6DCbmD3nr4R6V5E7VSmtbwh8GVqTqVRU1S4LoJjM0rSPuyo='

with open('config/email_body.html','r') as file:
    HTML_BODY = file.readline()

retrieved_key = dbc.retrieve_key()
cipher = Fernet(retrieved_key)
OUTBND_PSWD = cipher.decrypt(OUTBND_ENC_PSWD)
OUTBND_PSWD = OUTBND_PSWD.decode('utf-8')

def registration_email(firstname:str, email:str, username:str, password:str) -> bool:
    '''
    Function to trigger the registration email to a new system user.
    Takes as input the firstname, email and autogenerated password.
    Sends a notification to the given email containing the password for the created user.
    '''
    subject = f'Welcome to the NCSC Suspect Sources System, {firstname}!'
    email_body = f"""
                <p><strong>Welcome, {firstname}</strong>!</p>
                <p>You may now log into the Suspect Sources Interface using the following credentials:</p>
                <p><span style="color: #000080;"><strong>Username:</strong></span> <strong>{username}</strong><br /> 
                <span style="color: #000080;"><strong>Password:</strong></span> <strong>{password}</strong></p>
                <p>Please note, that you will be prompted to change your password once you log into the system for the first time. 
                This is done to enhance the security of your account.<br />
                Please don't hesitate to contact a system administrator or the technical support team should you run into any difficulties.</p>
                """
    my_email = MIMEText(HTML_BODY.replace('{CONTENT}', email_body), "html")
    my_email["From"] = OUTBND_EMAIL
    my_email["To"] = email
    my_email["Subject"] = subject
    try:
        server = smtplib.SMTP("smtp.gmail.com")
        server.starttls()
        server.login(user=OUTBND_EMAIL, password=OUTBND_PSWD)
        server.sendmail(OUTBND_EMAIL, email, my_email.as_string())
    except smtplib.SMTPException:
        return False
    return True


def new_source_email(
    recipient_list:list, source_id:id, source_name:str, source_url:str, source_threat_level:int
) -> bool:
    '''
    Function to trigger the notification when a new suspect source has been added to the system.
    Takes as input a list of tuples containing the email:firstname pair
    of all users in the system with the role "Authority".
    Also takes the information of the added source, such as the id, name, url and threat level.
    Sends a notification to all emails in the tuple with details of the newly added suspect source.
    Please note recipient_list structure should be:
    [('email1@email.com', 'firstname1'), ('email2@email.com', 'firstname2')]
    '''
    subject = f'New Suspect Source has been added: {source_name}'
    email_body = f"""
                <p><strong>Dear&nbsp;FIRSTNAME,</strong></p>
                <p>This email serves as a notification that a new suspect source has been added to the NCSC Suspect Sources System.</p>
                <p>Overview of the added source:</p>
                <p><span style="color: #0000ff;"><strong>Source Name:</strong></span> <strong>{source_name}</strong><br /> 
                <span style="color: #0000ff;"><strong>Source ID:</strong></span> <strong>{source_id}</strong><br /> <strong>
                <span style="color: #0000ff;"><strong>Source URL:</strong></span> {source_url}<br /> <strong>
                <span style="color: #0000ff;">Source Threat Level:</span> {source_threat_level}</strong></p>
                <p>Please log into the system and search for the threat id to obtain a full description of the newly added suspect source.</p>
                <p>Please don't hesitate to contact a system administrator or the technical support team should you run into any difficulties.</p>
                """
    for item in recipient_list:
        email = item[0]
        first_name = item[1]
        content = email_body.replace('FIRSTNAME', first_name)
        my_email = MIMEText(HTML_BODY.replace('{CONTENT}', content), "html")
        my_email["From"] = OUTBND_EMAIL
        my_email["To"] = email
        my_email["Subject"] = subject
        try:
            server = smtplib.SMTP("smtp.gmail.com")
            server.starttls()
            server.login(user=OUTBND_EMAIL, password=OUTBND_PSWD)
            server.sendmail(OUTBND_EMAIL, email, my_email.as_string())
        except smtplib.SMTPException:
            return False
        print(GREEN + f"Sent Notification successfully to: {first_name} at {email}") # Debug Line to check email sends
    return True


def changed_password_email(firstname:str, email:str) -> bool:
    '''
    Function to trigger a notification email if the password of a user is changed. Takes as input the firstname and email of the user.
    Will send an email to the email given as an arg to confirm that the password has been changed.
    '''
    subject = 'Password Changed Successfully'
    email_body = f"""
                <p><strong>Dear&nbsp;{firstname},</strong></p>
                <p>This email is to notify you of a successful password change to your NCSC Suspect Sources account.
                 You are now able to log in with your username and newly set password.</p>
                <p>If you did not action this change, please contact the NCSC Administrator Team immediately. In this case, your account might be comprised.</p>
                """
    my_email = MIMEText(HTML_BODY.replace('{CONTENT}', email_body), "html")
    my_email["From"] = OUTBND_EMAIL
    my_email["To"] = email
    my_email["Subject"] = subject
    try:
        server = smtplib.SMTP("smtp.gmail.com")
        server.starttls()
        server.login(user=OUTBND_EMAIL, password=OUTBND_PSWD)
        server.sendmail(OUTBND_EMAIL, email, my_email.as_string())
    except smtplib.SMTPException:
        return False
    return True
